language: java
sudo: true
jdk:
- openjdk11
script: "./mvnw clean package"
addons:
  ssh_known_hosts: 161.35.122.230
notifications: email:carlostapiam@gmail.com
before_install:
- openssl aes-256-cbc -K $encrypted_e79cab55eab4_key -iv $encrypted_e79cab55eab4_iv
  -in vicky.enc -out vicky -d
- chmod a+x ./mvnw
install:
- "./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
deploy:
  provider: releases
  file: vicky.jar
  skip_cleanup: true
  on:
    branch: master
