language: java
sudo: true
jdk:
- openjdk11
script: "./mvnw clean package"
addons:
  ssh_known_hosts: 161.35.122.230
notifications: email:carlostapiam@gmail.com
before_install:
- openssl aes-256-cbc -K $encrypted_faf3d0b2ca4b_key -iv $encrypted_faf3d0b2ca4b_iv
  -in ctapia_rsa.enc -out ctapia_rsa -d
- openssl aes-256-cbc -K $encrypted_e8324199bea4_key -iv $encrypted_e8324199bea4_iv
  -in ctapia.enc -out ctapia -d
- chmod a+x ./mvnw
install:
- "./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
deploy:
  provider: releases
  file: vicky.jar
  skip_cleanup: true
  on:
    branch: master
