language: java
sudo: true
jdk:
- openjdk11
  #script: "./mvnw clean package"
#addons:
# ssh_known_hosts: 161.35.122.230

notifications:
 email:carlostapiam@gmail.com

before_install:
- openssl aes-256-cbc -K $encrypted_e79cab55eab4_key -iv $encrypted_e79cab55eab4_iv
  -in vicky.enc -out  ~/.ssh/vicky -d
- pwd
- ls -la
- chmod 644 ~/.ssh/known_hosts
- chmod 755 ~/.ssh
- chmod 600 ~/.ssh/vicky
- chmod a+x ./mvnw

install:
- "./mvnw clean package -DskipTests=true -Dmaven.javadoc.skip=true -B -V"

env:
 global:
  - REMOTEAPPDIR=/home/ctapia/backend/
  - REMOTEUSER=ctapia
  - REMOTEHOST=161.35.122.230
  - PORT=8080

deploy:
 provider: script
 #file: vicky.jar
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 script: bash scripts/deploy.sh
 on:
  branch: master

#after_success:
# - bash ./deploy.sh
