language: java
jdk:
 - openjdk11
script: ./mvnw clean package

notifications:
 email:carlostapiam@gmail.com

before_script:   
 - chmod a+x ./mvnw

install:
 - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
